# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 901)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_mode.setGeometry(QtCore.QRect(10, 50, 120, 80))
        self.groupBox_mode.setStyleSheet("font: 25 10pt \"Microsoft YaHei\";")
        self.groupBox_mode.setObjectName("groupBox_mode")
        self.radioButton_pasv = QtWidgets.QRadioButton(self.groupBox_mode)
        self.radioButton_pasv.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.radioButton_pasv.setChecked(True)
        self.radioButton_pasv.setObjectName("radioButton_pasv")
        self.radioButton_port = QtWidgets.QRadioButton(self.groupBox_mode)
        self.radioButton_port.setGeometry(QtCore.QRect(20, 50, 91, 21))
        self.radioButton_port.setObjectName("radioButton_port")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 951, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_IP = QtWidgets.QLabel(self.splitter)
        self.label_IP.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_IP.setObjectName("label_IP")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label_port = QtWidgets.QLabel(self.splitter)
        self.label_port.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_port.setObjectName("label_port")
        self.lineEdit_port = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.label_username = QtWidgets.QLabel(self.splitter)
        self.label_username.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_username.setObjectName("label_username")
        self.lineEdit_username = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_password = QtWidgets.QLabel(self.splitter)
        self.label_password.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 570, 1081, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("font: 25 14pt \"Microsoft YaHei\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.tableWidget_uploadQueue = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_uploadQueue.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.tableWidget_uploadQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_uploadQueue.setObjectName("tableWidget_uploadQueue")
        self.tableWidget_uploadQueue.setColumnCount(0)
        self.tableWidget_uploadQueue.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_uploadQueue, 1, 0, 1, 1)
        self.tableWidget_downloadQueue = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_downloadQueue.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.tableWidget_downloadQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_downloadQueue.setObjectName("tableWidget_downloadQueue")
        self.tableWidget_downloadQueue.setColumnCount(0)
        self.tableWidget_downloadQueue.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_downloadQueue, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 140, 1091, 411))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_serverFile = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_serverFile.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";")
        self.groupBox_serverFile.setObjectName("groupBox_serverFile")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_serverFile)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_pathText = QtWidgets.QLabel(self.groupBox_serverFile)
        self.label_pathText.setObjectName("label_pathText")
        self.gridLayout_2.addWidget(self.label_pathText, 0, 0, 1, 1)
        self.label_path = QtWidgets.QLabel(self.groupBox_serverFile)
        self.label_path.setObjectName("label_path")
        self.gridLayout_2.addWidget(self.label_path, 0, 1, 1, 1)
        self.pushButton_goback = QtWidgets.QPushButton(self.groupBox_serverFile)
        self.pushButton_goback.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_goback.setObjectName("pushButton_goback")
        self.gridLayout_2.addWidget(self.pushButton_goback, 1, 0, 1, 1)
        self.pushButton_upload = QtWidgets.QPushButton(self.groupBox_serverFile)
        self.pushButton_upload.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.gridLayout_2.addWidget(self.pushButton_upload, 1, 1, 1, 1)
        self.pushButton_makedir = QtWidgets.QPushButton(self.groupBox_serverFile)
        self.pushButton_makedir.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_makedir.setObjectName("pushButton_makedir")
        self.gridLayout_2.addWidget(self.pushButton_makedir, 1, 2, 1, 1)
        self.tableWidget_ServerFile = QtWidgets.QTableWidget(self.groupBox_serverFile)
        self.tableWidget_ServerFile.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.tableWidget_ServerFile.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ServerFile.setObjectName("tableWidget_ServerFile")
        self.tableWidget_ServerFile.setColumnCount(0)
        self.tableWidget_ServerFile.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_ServerFile, 2, 0, 1, 3)
        self.horizontalLayout.addWidget(self.groupBox_serverFile)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";")
        self.groupBox.setObjectName("groupBox")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(10, 30, 521, 371))
        self.listView.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.groupBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(180, 50, 631, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_connect = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_connect.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_2.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_disconnect.setEnabled(False)
        self.pushButton_disconnect.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.horizontalLayout_2.addWidget(self.pushButton_disconnect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_SYST = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_SYST.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_SYST.setObjectName("pushButton_SYST")
        self.horizontalLayout_2.addWidget(self.pushButton_SYST)
        self.pushButton_TYPE = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_TYPE.setStyleSheet("font: 15pt \"SimSun-ExtB\";")
        self.pushButton_TYPE.setObjectName("pushButton_TYPE")
        self.horizontalLayout_2.addWidget(self.pushButton_TYPE)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_connect.clicked.connect(MainWindow.connect_server)
        self.pushButton_SYST.clicked.connect(MainWindow.syst_query)
        self.pushButton_TYPE.clicked.connect(MainWindow.type_query)
        self.radioButton_pasv.toggled['bool'].connect(MainWindow.mode_change)
        self.pushButton_disconnect.clicked.connect(MainWindow.disconnect_server)
        self.pushButton_upload.clicked.connect(MainWindow.uploadFile)
        self.pushButton_goback.clicked.connect(MainWindow.openDirectory)
        self.pushButton_makedir.clicked.connect(MainWindow.makeDirectory)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_mode.setTitle(_translate("MainWindow", "文件传输模式"))
        self.radioButton_pasv.setText(_translate("MainWindow", "PASV"))
        self.radioButton_port.setText(_translate("MainWindow", "PORT"))
        self.label_IP.setText(_translate("MainWindow", "IP"))
        self.label_port.setText(_translate("MainWindow", "port"))
        self.label_username.setText(_translate("MainWindow", "username"))
        self.label_password.setText(_translate("MainWindow", "password"))
        self.label_2.setText(_translate("MainWindow", "uploadQueue"))
        self.label_3.setText(_translate("MainWindow", "downloadQueue"))
        self.groupBox_serverFile.setTitle(_translate("MainWindow", "ServerFile"))
        self.label_pathText.setText(_translate("MainWindow", "Currentpath"))
        self.label_path.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_goback.setText(_translate("MainWindow", "go back"))
        self.pushButton_upload.setText(_translate("MainWindow", "upload"))
        self.pushButton_makedir.setText(_translate("MainWindow", "make dir"))
        self.groupBox.setTitle(_translate("MainWindow", "ServerResponse"))
        self.pushButton_connect.setText(_translate("MainWindow", "connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "disconnect"))
        self.pushButton_SYST.setText(_translate("MainWindow", "SYST"))
        self.pushButton_TYPE.setText(_translate("MainWindow", "TYPE"))
